/*
 * jquant1.c
 *
 * Copyright (C) 1991, 1992, Thomas G. Lane.
 * This file is part of the Independent JPEG Group's software.
 * For conditions of distribution and use, see the accompanying README file.
 *
 * This file contains 1-pass color quantization (color mapping) routines.
 * These routines are invoked via the methods color_quantize
 * and color_quant_init/term.
 */

#include "jinclude.h"

#ifdef QUANT_1PASS_SUPPORTED


/*
 * The main purpose of 1-pass quantization is to provide a fast, if not very
 * high quality, colormapped output capability.  A 2-pass quantizer usually
 * gives better visual quality; however, for quantized grayscale output this
 * quantizer is perfectly adequate.  Dithering is highly recommended with this
 * quantizer, though you can turn it off if you really want to.
 *
 * This implementation quantizes in the output colorspace.  This has a couple
 * of disadvantages: each pixel must be individually color-converted, and if
 * the color conversion includes gamma correction then quantization is done in
 * a nonlinear space, which is less desirable.  The major advantage is that
 * with the usual output color spaces (RGB, grayscale) an orthogonal grid of
 * representative colors can be used, thus permitting the very simple and fast
 * color lookup scheme used here.  The standard JPEG colorspace (YCbCr) cannot
 * be effectively handled this way, because only about a quarter of an
 * orthogonal grid would fall within the gamut of realizable colors.  Another
 * advantage is that when the user wants quantized grayscale output from a
 * color JPEG file, this quantizer can provide a high-quality result with no
 * special hacking.
 *
 * The gamma-correction problem could be eliminated by adjusting the grid
 * spacing to counteract the gamma correction applied by color_convert.
 * At this writing, gamma correction is not implemented by jdcolor, so
 * nothing is done here.
 *
 * In 1-pass quantization the colormap must be chosen in advance of seeing the
 * image.  We use a map consisting of all combinations of Ncolors[i] color
 * values for the i'th component.  The Ncolors[] values are chosen so that
 * their product, the total number of colors, is no more than that requested.
 * (In most cases, the product will be somewhat less.)
 *
 * Since the colormap is orthogonal, the representative value for each color
 * component can be determined without considering the other components;
 * then these indexes can be combined into a colormap index by a standard
 * N-dimensional-array-subscript calculation.  Most of the arithmetic involved
 * can be precalculated and stored in the lookup table colorindex[].
 * colorindex[i][j] maps pixel value j in component i to the nearest
 * representative value (grid plane) for that component; this index is
 * multiplied by the array stride for component i, so that the
 * index of the colormap entry closest to a given pixel value is just
 *    sum( colorindex[component-number][pixel-component-value] )
 * Aside from being fast, this scheme allows for variable spacing between
 * representative values with no additional lookup cost.
 */


/* Declarations for ordered dithering.
 *
 * We use a standard 16x16 ordered dither array.  The basic concept of ordered
 * dithering is described in many references, for instance Dale Schumacher's
 * chapter II.2 of Graphics Gems II (James Arvo, ed. Academic Press, 1991).
 * For ordered dithering, we assume that the output colors are equally spaced;
 * if not, results will probably be worse, since the dither may be too much
 * or too little at a given point.
 */

static JSAMPLE dithermatrix[16][16] = {
  /* Bayer's order-4 dither array.  Generated by the code given in
   * Stephen Hawley's article "Ordered Dithering" in Graphics Gems I.
   * The values in this array must range from 0 to 16*16-1.
   */
    0,192, 48,240, 12,204, 60,252,  3,195, 51,243, 15,207, 63,255,
  128, 64,176,112,140, 76,188,124,131, 67,179,115,143, 79,191,127,
   32,224, 16,208, 44,236, 28,220, 35,227, 19,211, 47,239, 31,223,
  160, 96,144, 80,172,108,156, 92,163, 99,147, 83,175,111,159, 95,
    8,200, 56,248,  4,196, 52,244, 11,203, 59,251,  7,199, 55,247,
  136, 72,184,120,132, 68,180,116,139, 75,187,123,135, 71,183,119,
   40,232, 24,216, 36,228, 20,212, 43,235, 27,219, 39,231, 23,215,
  168,104,152, 88,164,100,148, 84,171,107,155, 91,167,103,151, 87,
    2,194, 50,242, 14,206, 62,254,  1,193, 49,241, 13,205, 61,253,
  130, 66,178,114,142, 78,190,126,129, 65,177,113,141, 77,189,125,
   34,226, 18,210, 46,238, 30,222, 33,225, 17,209, 45,237, 29,221,
  162, 98,146, 82,174,110,158, 94,161, 97,145, 81,173,109,157, 93,
   10,202, 58,250,  6,198, 54,246,  9,201, 57,249,  5,197, 53,245,
  138, 74,186,122,134, 70,182,118,137, 73,185,121,133, 69,181,117,
   42,234, 26,218, 38,230, 22,214, 41,233, 25,217, 37,229, 21,213,
  170,106,154, 90,166,102,150, 86,169,105,153, 89,165,101,149, 85
};


/* Declarations for Floyd-Steinberg dithering.
 *
 * Errors are accumulated into the array fserrors[], at a resolution of
 * 1/16th of a pixel count.  The error at a given pixel is propagated
 * to its not-yet-processed neighbors using the standard F-S fractions,
 *		...	(here)	7/16
 *		3/16	5/16	1/16
 * We work left-to-right on even rows, right-to-left on odd rows.
 *
 * We can get away with a single array (holding one row's worth of errors)
 * by using it to store the current row's errors at pixel columns not yet
 * processed, but the next row's errors at columns already processed.  We
 * need only a few extra variables to hold the errors immediately around the
 * current column.  (If we are lucky, those variables are in registers, but
 * even if not, they're probably cheaper to access than array elements are.)
 *
 * The fserrors[] array is indexed [component#][position].
 * We provide (#columns + 2) entries per component; the extra entry at each
 * end saves us from special-casing the first and last pixels.
 *
 * Note: on a wide image, we might not have enough room in a PC's near data
 * segment to hold the error array; so it is allocated with alloc_large.
 */

#ifdef EIGHT_BIT_SAMPLES
typedef INT16 FSERROR;		/* 16 bits should be enough */
#else
typedef INT32 FSERROR;		/* may need more than 16 bits? */
#endif

typedef FSERROR FAR *FSERRPTR;	/* pointer to error array (in FAR storage!) */

typedef struct
{
  JSAMPROW colorindex;	/* Precomputed mapping for speed */
/* colorindex[i][j] = index of color closest to pixel value j in component i,
 * premultiplied as described above.  Since colormap indexes must fit into
 * JSAMPLEs, the entries of this array will too.
 */
  JSAMPROW colorset;
  FSERRPTR fserrors; /* accumulated errors */
  FSERRPTR dummy;
}
FSBUF;

static FSBUF *fs;


static long on_which_row;	/* flag to remember which row we are on */


/*
 * Policy-making subroutines for color_quant_init: these routines determine
 * the colormap to be used.  The rest of the module only assumes that the
 * colormap is orthogonal.
 *
 *  * select_ncolors decides how to divvy up the available colors
 *    among the components.
 *  * output_value defines the set of representative values for a component.
 *  * largest_input_value defines the mapping from input values to
 *    representative values for a component.
 * Note that the latter two routines may impose different policies for
 * different components, though this is not currently done.
 */


LOCAL int
select_ncolors (decompress_info_ptr cinfo, int Ncolors[])
/* Determine allocation of desired colors to components, */
/* and fill in Ncolors[] array to indicate choice. */
/* Return value is total number of colors (product of Ncolors[] values). */
{
  int nc = cinfo->color_out_comps; /* number of color components */
  int max_colors = cinfo->desired_number_of_colors;
  int iroot, i, temp, total_colors;

  /* We can allocate at least the nc'th root of max_colors per component. */
  /* Compute floor(nc'th root of max_colors). */
  temp = iroot = 1;
  do {
    ++iroot; total_colors = temp;
    if (temp >= max_colors) break;
    i = nc; temp = 1;		/* set temp = iroot ** nc */
    do temp *= iroot; while (--i > 0);
  } while (temp <= max_colors);	/* repeat till iroot exceeds root */
  --iroot;			/* now iroot = floor(root) */

  /* Must have at least 2 color values per component */
  if (iroot < 2)
    ERREXIT1(cinfo->emethods, "Cannot quantize to fewer than %d colors",
	     temp);

  /* Initialize to iroot color values for each component */
  do *Ncolors++ = iroot; while (--nc > 0);

  return total_colors;
}


/*
 * Initialize for one-pass color quantization.
 */

METHODDEF void
color_quant_init (decompress_info_ptr cinfo)
{
  int i, j, blksize, blkdist, val;
  int *nci;			/* # of values alloced to each component */
  long fs_width;
  JSAMPROW p;

  on_which_row = 0; if (cinfo->use_dithering == 0) return;
  on_which_row += sizeof(JSAMPLE);

  fs_width = (cinfo->image_width + 2) * sizeof(FSERROR);

  fs = (FSBUF *)(*cinfo->emethods->alloc_small)
	(((sizeof(FSBUF) + sizeof(JSAMPROW) + sizeof(int)
	  + (MAXJSAMPLE+1) * 3 * sizeof(JSAMPLE))
	   + fs_width) * cinfo->color_out_comps);

  cinfo->colormap = (JSAMPARRAY)(fs + cinfo->color_out_comps);
  nci = (int *)(cinfo->colormap + cinfo->color_out_comps);
  p = (JSAMPROW)(nci + cinfo->color_out_comps);

  /* Initialize Floyd-Steinberg workspace */

  for (i = 0; i < cinfo->color_out_comps; i++) {
    /* Initialize the propagated errors to zero. */
    MEMZERO(p, fs_width);
    fs[i].fserrors = (FSERRPTR)p; (char *)p += fs_width;
  }

  if ((cinfo->actual_number_of_colors = cinfo->desired_number_of_colors) > 0 &&
       cinfo->actual_number_of_colors <= MAXJSAMPLE + 1)
  {
  /* Select number of colors for each component */
  cinfo->actual_number_of_colors = select_ncolors(cinfo, nci);

  /* Report selected color counts */
  if (cinfo->color_out_comps == 3)
    TRACEMS4(cinfo->emethods, 1, "Quantizing to %d = %d*%d*%d colors",
	     cinfo->actual_number_of_colors, nci[0], nci[1], nci[2]);
  else
    TRACEMS1(cinfo->emethods, 1, "Quantizing to %d colors",
	     cinfo->actual_number_of_colors);

  /* Allocate and fill in the colormap and color index. */
  /* The colors are ordered in the map in standard row-major order, */
  /* i.e. rightmost (highest-indexed) color changes most rapidly. */

  /* blksize is number of adjacent repeated entries for a component */
  /* blkdist is distance between groups of identical entries for a component */
  blkdist = cinfo->actual_number_of_colors;

  for (i = 0; i < cinfo->color_out_comps; i++) {
    /* fill in colormap entries for i'th color component */
    blksize = blkdist / *nci;
    j = --*nci;
    do {
      int ptr;
		/* Compute j'th output value (out of nci) for component */
#ifdef EIGHT_BIT_SAMPLES
      val = (j * 2 * MAXJSAMPLE + *nci) / (*nci * 2);
#else
      val = (int)(((long)j * 2 * MAXJSAMPLE + *nci) / (*nci * 2));
#endif
      /* Fill in all colormap entries that have this value of this component */
      for (ptr = j * blksize; ptr < cinfo->actual_number_of_colors;
	   ptr += blkdist) {
	/* fill in blksize entries beginning at ptr */
	int k = blksize;
	while (--k >= 0) p[ptr+k] = (JSAMPLE) val;
      }
    }
    while (--j >= 0);
    cinfo->colormap[i] = p; p += MAXJSAMPLE + 1;
    fs[i].colorindex = p;

    /* fill in colorindex entries for i'th color component */
    /* in loop, val = index of current output value */
    {
#ifdef EIGHT_BIT_SAMPLES
    int
#else
    long
#endif
    k = 0, limit = CENTERJSAMPLE;
    val = j = 0;
    do {
      while (k > limit) {	/* advance val if past boundary */
	limit += MAXJSAMPLE; val += blksize;
      }
      *p++ = (JSAMPLE) val; k += *nci;
    }
    while (++j <= MAXJSAMPLE);
    }
    blkdist = blksize;		/* blksize of this color is blkdist of next */
    nci++;
  }
  }
  /* Pass the colormap to the output module. */
  /* NB: the output module may continue to use the colormap until shutdown. */
  (*cinfo->put_color_map)
   (cinfo, cinfo->actual_number_of_colors, cinfo->colormap);

  if (cinfo->actual_number_of_colors > 0 &&
      cinfo->actual_number_of_colors <= MAXJSAMPLE + 1)
    while (--i >= 0) {
      fs[i].colorset = p;
      for (j = 0; j <= MAXJSAMPLE; j++)
	*p++ = cinfo->colormap[i][fs[i].colorindex[j]];
    }
  else
    while (--i >= 0)
      fs[i].colorset = cinfo->colormap[i];
}


METHODDEF void
gray_quantize1 (decompress_info_ptr cinfo, int num_rows,
		JSAMPIMAGE pixel_data, ...)
{
  long drow, dcol, col, width = cinfo->image_width;
  JSAMPLE one, *ptr, *dith_ptr, **pix_arr = *pixel_data;

  drow = on_which_row; one = 1;
  do
  { ptr = *pix_arr++;
    dith_ptr = dithermatrix[drow];
    col = width; dcol = 15;
    ++drow; drow &= dcol;
    for (;;)
    {
      if (*dith_ptr++ < *ptr) *ptr++ = one; else *ptr++ = 0;
      if (--col <= 0) break;
      if (--dcol >= 0) continue;
      dcol = 15; dith_ptr -= 16;
  } }
  while (--num_rows > 0);
  on_which_row = drow;
}


METHODDEF void
gray_quantize8 (decompress_info_ptr cinfo, int num_rows,
		JSAMPIMAGE pixel_data, ...)
{
  int val;
  long drow, dcol, col, width = cinfo->image_width;
  JSAMPLE *ptr, *dith_ptr, **pix_arr = *pixel_data;
  static JSAMPLE idx[] = { 0,43,2*43,3*43,4*43,5*43 };

  drow = on_which_row;
  do
  { ptr = *pix_arr++;
    dith_ptr = dithermatrix[drow];
    col = width; dcol = 15;
    ++drow; drow &= dcol;
    for (;;)
    {
      val = *ptr; val += val << 2;
      if ((unsigned char)*dith_ptr < (unsigned char)val) val += 256;
      val >>= 8; dith_ptr++;
      *ptr++ = idx[val];
      if (--col <= 0) break;
      if (--dcol >= 0) continue;
      dcol = 15; dith_ptr -= 16;
  } }
  while (--num_rows > 0);
  on_which_row = drow;
}


METHODDEF void
color_quantize3 (decompress_info_ptr cinfo, int num_rows,
		 JSAMPIMAGE pixel_data, ...)
{
  long drow, row, dcol, col, width = cinfo->image_width;
  JSAMPLE dith, pixcode, *ptr0, *ptr1, *ptr2, *dith_ptr;

  drow = on_which_row; row = 0;
  do
  { ptr0 = pixel_data[0][row];
    ptr1 = pixel_data[1][row];
    ptr2 = pixel_data[2][row];
    dith_ptr = dithermatrix[drow];
    col = width; dcol = 15;
    ++drow; drow &= dcol;
    for (;;)
    {
      dith = *dith_ptr++; pixcode = 0;
      if (dith < *ptr0  ) pixcode += 4;
      if (dith < *ptr1++) pixcode += 2;
      if (dith < *ptr2++) pixcode += 1;
      *ptr0++ = pixcode;
      if (--col <= 0) break;
      if (--dcol >= 0) continue;
      dcol = 15; dith_ptr -= 16;
  } }
  while (++(int)row < num_rows);
  on_which_row = drow;
}


METHODDEF void
color_quantize8 (decompress_info_ptr cinfo, int num_rows,
		 JSAMPIMAGE pixel_data, ...)
{
  int val;
  long row, dcol, col, width = cinfo->image_width;
  JSAMPLE dith, pixcode, *ptr0, *ptr1, *ptr2, *dith_ptr;

  row = 0;
  do
  { ptr0 = pixel_data[0][row];
    ptr1 = pixel_data[1][row];
    ptr2 = pixel_data[2][row];
    col = on_which_row;
    dith_ptr = dithermatrix[col];
    dcol = 15; ++col; col &= dcol;
    on_which_row = col; col = width;
    for (;;)
    {
      dith = *dith_ptr++; pixcode = 0;
      val = *ptr0;   val += val << 2;
      if ((unsigned char)dith < (unsigned char)val) ++pixcode;
      val >>= 8; pixcode += (JSAMPLE)val;
      pixcode += pixcode << 1; pixcode <<= 1;
      val = *ptr1++; val += val << 2;
      if ((unsigned char)dith < (unsigned char)val) ++pixcode;
      val >>= 8; pixcode += (JSAMPLE)val;
      pixcode += pixcode << 1; pixcode <<= 1;
      val = *ptr2++; val += val << 2;
      if ((unsigned char)dith < (unsigned char)val) ++pixcode;
      val >>= 8; pixcode += (JSAMPLE)val;
      *ptr0++ = pixcode;
      if (--col <= 0) break;
      if (--dcol >= 0) continue;
      dcol = 15; dith_ptr -= 16;
  } }
  while (++(int)row < num_rows);
}


LOCAL void
do_color_quantize_dither (decompress_info_ptr cinfo, int num_rows,
			  JSAMPIMAGE pixel_data)
/* General case, with Floyd-Steinberg dithering */
{
  int nc = cinfo->color_out_comps;
  long ci, col, row, width = cinfo->image_width;
  JSAMPROW range_limit = cinfo->sample_range_limit;
  JSAMPROW colorindex_ci, colorset_ci, ptr;
  FSERRPTR fserrors_ci;
  FSERROR cur;			/* current error or pixel value */
  FSERROR belowerr;		/* error for pixel below cur */
  FSERROR bpreverr;		/* error for below/prev col */
  FSERROR val;
  long dir = on_which_row;	/* + for left-to-right, - for right-to-left */

  row = 0;
  do
  { ci = 0;
    do
    { colorindex_ci = fs[ci].colorindex;
      colorset_ci = fs[ci].colorset;
      fserrors_ci = fs[ci].fserrors;
      ptr = pixel_data[ci][row]; col = width;
      if (dir < 0)
      {
        fserrors_ci += col+1;
	ptr += col-1;
      }
      /* Preset error values: no error propagated to first pixel from left */
      cur = 0;
      /* and no error propagated to row below yet */
      belowerr = bpreverr = 0;
      do
      { /* cur holds the error propagated from the previous pixel on the
	 * current line.  Add the error propagated from the previous line
	 * to form the complete error correction term for this pixel, and
	 * round the error term (which is expressed * 16) to an integer.
	 * RIGHT_SHIFT rounds towards minus infinity, so adding 8 is correct
	 * for either sign of the error value.
	 * Note: errorptr points to *previous* column's array entry.
	 */
	cur += *(FSERROR *)((char *)fserrors_ci + dir); cur += 8; cur >>= 4;
	/* Form pixel value + error, and range-limit to 0..MAXJSAMPLE.
	 * The maximum error is +- MAXJSAMPLE; this sets the required size
	 * of the range_limit array.
	 */
	cur += *ptr; cur = range_limit[cur];
	*ptr = colorindex_ci[cur];	/* Select output value */
	/* Compute actual representation error at this pixel
	 * Note: we can do this even though we don't yet have the final
	 * value of pixcode, because the colormap is orthogonal.
	 */
	cur -= colorset_ci[cur];
	/* Compute error fractions to be propagated to adjacent pixels.
	 * Add these into the running sums, and simultaneously shift the
	 * next-line error sums left by 1 column.
	 */
	val = cur << 1;  cur += val;	/* form error * 3 */
	bpreverr += cur; cur += val;	/* form error * 5 */
	belowerr += cur; cur += val;	/* form error * 7 */
	*fserrors_ci = bpreverr;
	bpreverr = belowerr;
	belowerr = val >> 1;
	/* At this point cur contains the 7/16 error value to be propagated to
	 * the next pixel on the current line, and all the errors for the next
	 * line have been shifted over. We are therefore ready to move on.
	 */
	(char *)fserrors_ci += dir; /* advance errorptr to current column */
	(char *)ptr += dir;	/* advance ptr to next column */
      }
      while (--col > 0);
      /* Post-loop cleanup: we must unload the final error value into the
       * final fserrors[] entry.  Note we need not unload belowerr because
       * it is for the dummy column before or after the actual array.
       */
      *fserrors_ci = bpreverr;	/* unload prev err into array */
    }
    while (++(int)ci < nc);
    dir = -dir;
  }
  while (++(int)row < num_rows);
  on_which_row = dir;
}


METHODDEF void
color_quantize_dither (decompress_info_ptr cinfo, int num_rows,
		       JSAMPIMAGE pixel_data, ...)
/* General case, with Floyd-Steinberg dithering */
{
  do_color_quantize_dither(cinfo, num_rows, pixel_data);

  if (cinfo->color_out_comps == 3)
  {
    long row = 0, width = cinfo->image_width;
    do
    { JSAMPROW ptr0 = pixel_data[0][row];
      JSAMPROW ptr1 = pixel_data[1][row];
      JSAMPROW ptr2 = pixel_data[2][row];
      long col = width;
      do *ptr0++ += *ptr1++ + *ptr2++; while (--col > 0);
    }
    while (++(int)row < num_rows);
  }
  else if (cinfo->color_out_comps != 1)
  {
    long row = 0, width = cinfo->image_width;
    do
    { long col = width;
      do
      { JSAMPIMAGE pd = pixel_data + cinfo->color_out_comps;
	JSAMPROW ptr;
	JSAMPLE sum = 0;
	do
	{ ptr = (*--pd)[row];
	  sum += ptr[col];
	}
	while (pd != pixel_data);
	ptr[col] = sum;
      }
      while (--col > 0);
    }
    while (++(int)row < num_rows);
} }


METHODDEF void
color_quantize_dither2 (decompress_info_ptr cinfo, int num_rows,
			JSAMPIMAGE pixel_data, ...)
{
  int nc = cinfo->color_out_comps;
  long ci, col, row, width = cinfo->image_width;
  JSAMPROW range_limit = cinfo->sample_range_limit;
  JSAMPROW colorset_ci, ptr;
  FSERRPTR fserrors_ci;
  FSERROR cur, belowerr, bpreverr, val;
  long dir = on_which_row;

  row = 0;
  do
  { ci = 0;
    do
    { colorset_ci = fs[ci].colorset;
      fserrors_ci = fs[ci].fserrors;
      ptr = pixel_data[ci][row]; col = width;
      if (dir < 0)
      {
        fserrors_ci += col+1;
	ptr += col-1;
      }
      cur = belowerr = bpreverr = 0;
      do
      { cur += *(FSERROR *)((char *)fserrors_ci + dir);
	cur += 8; cur >>= 4;
	cur += *ptr; cur = range_limit[cur];
	*ptr = (JSAMPLE)cur;
	cur -= colorset_ci[cur];
	val = cur << 1;  cur += val;
	bpreverr += cur; cur += val;
	belowerr += cur; cur += val;
	*fserrors_ci = bpreverr;
	bpreverr = belowerr;
	belowerr = val >> 1;
	(char *)fserrors_ci += dir;
	(char *)ptr += dir;
      }
      while (--col > 0);
      *fserrors_ci = bpreverr;
    }
    while (++(int)ci < nc);
    dir = -dir;
  }
  while (++(int)row < num_rows);
  on_which_row = dir;
}


/*
 * Finish up at the end of the file.
 */

METHODDEF void
color_quant_term (decompress_info_ptr cinfo)
{
  /* no work (we let free_all release the workspace) */
  /* Note that we *mustn't* free the colormap before free_all, */
  /* since output module may use it! */
}


/*
 * The method selection routine for 1-pass color quantization.
 */

GLOBAL void
jsel1quantize (decompress_info_ptr cinfo)
{
  cinfo->color_quant_init = color_quant_init;
  cinfo->color_quantize = color_quantize_dither;
  cinfo->color_quant_term = color_quant_term;
  if (cinfo->use_dithering == 0)
    switch (cinfo->desired_number_of_colors)
    {
      case 2:
	cinfo->color_quantize = gray_quantize1; return;
      case 6:
	cinfo->color_quantize = gray_quantize8; return;
      case 2*2*2:
	cinfo->color_quantize = color_quantize3; return;
      case 6*6*6:
	cinfo->color_quantize = color_quantize8; return;
      default:
	cinfo->use_dithering++;
    }
  if (cinfo->use_dithering)
  {
    if (cinfo->desired_number_of_colors <= 0 ||
	cinfo->desired_number_of_colors > MAXJSAMPLE + 1)
      cinfo->color_quantize = color_quantize_dither2;
} }

#endif /* QUANT_1PASS_SUPPORTED */
