/* Resource Datei Indizes fÅr CONFIG */

#define TREE1    0   /* Formular/Dialog */
#define OUTPAR   3   /* BOX in Baum TREE1 */
#define NUMBER   4   /* FBOXTEXT in Baum TREE1 */
#define TOALLPAR 6   /* BUTTON in Baum TREE1 */
#define RAND     9   /* FBOXTEXT in Baum TREE1 */
#define JA       12  /* BUTTON in Baum TREE1 */
#define QNORMAL  16  /* BUTTON in Baum TREE1 */
#define PASSEND  23  /* BUTTON in Baum TREE1 */
#define PIXEL    28  /* BUTTON in Baum TREE1 */
#define XBRUCH   34  /* BUTTON in Baum TREE1 */
#define YBRUCH   37  /* BUTTON in Baum TREE1 */
#define LINKS    42  /* BUTTON in Baum TREE1 */
#define OBEN     47  /* BUTTON in Baum TREE1 */
#define ALLPAR   50  /* BOX in Baum TREE1 */
#define OUTWIN   53  /* BUTTON in Baum TREE1 */
#define OUTINT   57  /* BUTTON in Baum TREE1 */
#define EXTSPOOL 59  /* FTEXT in Baum TREE1 */
#define DOVER    62  /* BUTTON in Baum TREE1 */
#define FONTDEF  67  /* BUTTON in Baum TREE1 */
#define DITHCOL  70  /* BUTTON in Baum TREE1 */
#define IFSEL    73  /* BUTTON in Baum TREE1 */
#define TOSNDPAR 74  /* BUTTON in Baum TREE1 */
#define TOOUTPAR 75  /* BUTTON in Baum TREE1 */
#define IFILE    76  /* FBOXTEXT in Baum TREE1 */
#define LOAD     77  /* BUTTON in Baum TREE1 */
#define SAVE     78  /* BUTTON in Baum TREE1 */
#define OK       79  /* BUTTON in Baum TREE1 */
#define ABBRUCH  80  /* BUTTON in Baum TREE1 */
#define MEM      83  /* STRING in Baum TREE1 */
#define TOT      84  /* STRING in Baum TREE1 */
